db:
  type: postgres
  host: localhost
  port: 5550
  username: lws
  password: lws
  database: lws
  entities: [ 'dist/**/*.entity{.ts,.js}' ]
  synchronize: true

jwt:
  secret: secret
  expiresIn: 60s

init:
  admin:
    primaryID: lws
    password: lws
