db:
  type: postgres
  host: lws-db
  port: 5432
  username: lws
  password: lws
  database: lws
  entities: [ 'dist/**/*.entity{.ts,.js}' ]
  synchronize: true

jwt:
  accessSecret: 4jyo7GjnpXlqkgANnoTlxRSBG6gzBzCJOHUhNPtYmfLW3yWEYfDZY1HCUwzmWoj8xIQ1H2yGhSUqqmDNsxwcbMyYz3bsGlKOCGxoqJ/+DLeh6bg8qbJMTdYJHgfzuu2Ueh7Bwu3ar13ICjD3jpisoRLkesH2tktWNuSVDbBwy3BOzJzZVzVeTxX1cJEZRVn2+DktVbnic8v6a42ZIG3o2ceZycpBdxUkNZHJF75wVSyV9IyQrAqdoeCWxdzc2Kh8ggstlQyUJj9+Csgs9FB/a7Mh5PxU2FLsC9nJ0IfEd49iJkdm7/Lwn20Y9lKtF4/Ey8/Wlm+Z3+QNxCBwmyHMKg==
  refreshSecret: WTZhXWqMt86zWVw8jmRKf7ME1hqtNnx1KcHme7t5EE9hWXCcLo9xsBL0YK7Yp/4uCl6IchyPdzEFsQ2fe7f1OG1O9bGCYiLRPRdz+BL3Tm0Cchq2Fn2XcgWef1HFDk2HSn6TiTKOSYXGO8+1k5XCcsCini82sObuezyxTowQz31vZdChzYjQiyYsLzoJYHj77FaT8iwWJhnmt/wbrNWgt3w/IqWG6q5SHHs/S6xsv0xy5RdYhPGQctMXgHEm04CnNUqfBfId7nF33V5JUmNGdrgWdaxNuqn6cBINa8hyE6sHAT9qzHX4XKTxQsAWR/gTSTxPonTm9y5+etknlK1fiA==
  accessExpiresIn: 7d
  refreshExpiresIn: 7d

init:
  admin:
    primaryID: lws
    password: lws
