db:
  type: postgres
  host: localhost
  port: 5550
  username: lws
  password: lws
  database: lws
  entities: [ 'dist/**/*.entity{.ts,.js}' ]
  synchronize: true

jwt:
  accessSecret:
  refreshSecret:
  accessExpiresIn: 60s
  refreshExpiresIn: 7d

init:
  admin:
    primaryID: lws
    password: lws
